apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: nodejsrunpipe
description: nodejs run pipeline
serialPipeline:
 stages:
 - targetId: test-run
   profiles: [test]
 - targetId: prod-run
   profiles: [prod]
   strategy:
     canary:
       runtimeConfig:
         cloudRun:
           automaticTrafficControl: true
       canaryDeployment:
          percentages: [10]
          verify: false
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: test-run
description: cloud run test service
run:
 location: projects/gyucegok-alto/locations/us-east1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod-run
description: cloud run prod service
run:
 location: projects/gyucegok-alto/locations/us-east1
