apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: nodejsgkepipe
description: nodejs gke pipeline
serialPipeline:
 stages:
 - targetId: testauto
   profiles: []
 - targetId: prodauto
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: testauto
description: autopilot test cluster
gke:
 cluster: projects/gyucegok-alto/locations/us-east1/clusters/testauto
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prodauto
description: autopilot prod cluster
gke:
 cluster: projects/gyucegok-alto/locations/us-east1/clusters/prodauto
