apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: cloud-run-app
profiles:
- name: test
  manifests:
    rawYaml:
    - ./knative-manifests/deploy-test.yaml
- name: prod
  manifests:
    rawYaml:
    - ./knative-manifests/deploy-prod.yaml
deploy:
  cloudrun: {}